services:
  smokeAndWhispers:
    container_name: smokeAndWhispers
    image: smoke_and_whispers
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4173:4173
